-- =====================================
-- FINAL UNION + TRANSACTION LOGIC
-- =====================================

USE WAREHOUSE chipmunk_wh;
USE DATABASE user_db_chipmunk;
USE SCHEMA SCHEMA_WEATHER;

BEGIN;

INSERT INTO WEATHER_FINAL
SELECT OBS_TS_UTC, LAT, LON, TEMP_C, NULL, 'OBS', CURRENT_TIMESTAMP()
FROM WEATHER_OBSERVATION_HOURLY

UNION ALL

SELECT FORECAST_TS_UTC, LAT, LON, NULL, PRED_TEMP_C, 'FCST', CURRENT_TIMESTAMP()
FROM FORECAST_OUTPUT;

COMMIT;