-- =========================================
-- FINAL UNION WITH SQL TRANSACTION
-- =========================================

USE WAREHOUSE chipmunk_wh;
USE DATABASE user_db_chipmunk;
USE SCHEMA SCHEMA_WEATHER;

BEGIN;

INSERT INTO WEATHER_FINAL
SELECT 
    OBS_TS_UTC,
    LAT,
    LON,
    TEMP_C,
    NULL AS PRED_TEMP_C,
    'OBS' AS RECORD_TYPE,
    CURRENT_TIMESTAMP()
FROM WEATHER_OBSERVATION_HOURLY

UNION ALL

SELECT
    FORECAST_TS_UTC,
    LAT,
    LON,
    NULL AS TEMP_C,
    PRED_TEMP_C,
    'FCST' AS RECORD_TYPE,
    CURRENT_TIMESTAMP()
FROM FORECAST_OUTPUT;

COMMIT;