-- =====================================
-- CREATE TABLES FOR LAB 1
-- =====================================

USE WAREHOUSE chipmunk_wh;
USE DATABASE user_db_chipmunk;
USE SCHEMA SCHEMA_WEATHER;

-- RAW TABLE
CREATE OR REPLACE TABLE OPEN_METEO_RAW (
    INGEST_ID STRING,
    INGEST_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    API_URL STRING,
    RESPONSE_JSON VARIANT
);

-- TRANSFORMED HOURLY TABLE
CREATE OR REPLACE TABLE WEATHER_OBSERVATION_HOURLY (
    OBS_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    TEMP_C FLOAT,
    REL_HUMIDITY_PCT FLOAT,
    WIND_SPEED_MS FLOAT,
    PRECIP_MM FLOAT,
    LOAD_TS_UTC TIMESTAMP_NTZ
);

-- FORECAST TABLE
CREATE OR REPLACE TABLE FORECAST_OUTPUT (
    FORECAST_TS_UTC TIMESTAMP_NTZ,
    ISSUED_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    PRED_TEMP_C FLOAT,
    MODEL_NAME STRING,
    MODEL_VERSION STRING,
    LOAD_TS_UTC TIMESTAMP_NTZ
);

-- FINAL TABLE
CREATE OR REPLACE TABLE WEATHER_FINAL (
    EVENT_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    TEMP_C FLOAT,
    PRED_TEMP_C FLOAT,
    RECORD_TYPE STRING,
    LOAD_TS_UTC TIMESTAMP_NTZ
);